#debug=true

# Common Kafka Properties
spring.kafka.bootstrap-servers=localhost:9092

# Producer Config
spring.kafka.producer.key-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer Config
spring.kafka.consumer.group-id=jackpot-group

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sporty.jackpot.service.model.*
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Log everything the Kafka Producer does
#logging.level.org.apache.kafka.clients.producer=DEBUG
#logging.level.org.apache.kafka.clients.NetworkClient=DEBUG


# Explicitly set the DataSource URL to prevent unique random names
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate/JPA settings for H2
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Options: update, create, create-drop, validate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.properties.hibernate.hbm2ddl.auto=update

# Enable the H2 Web Console 
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL in the logs
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Set logging levels to debug schema management
logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.root=INFO
logging.file.path=/var/log/jackpot/
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# Set swagger path
#server.servlet.context-path=/api
springdoc.swagger-ui.path=/swagger-ui.html